In [1]:
import pandas as pd

In [2]:
# load the data from excel file
df = pd.read_excel("Movies_Dataset.xlsx")
df

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
4       Movie 5     Action          2012          6.6  1205.51
..          ...        ...           ...          ...      ...
995   Movie 996     Sci-Fi          2013          8.7   456.39
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[1000 rows x 5 columns]

In [3]:
df.head()

  Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0    Movie 1     Sci-Fi          2000          6.0  1680.53
1    Movie 2  Adventure          2000          2.2   987.24
2    Movie 3    Romance          2002          5.2  1122.13
3    Movie 4    Romance          2001          4.5   581.84
4    Movie 5     Action          2012          6.6  1205.51

In [4]:
df.tail()

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
995   Movie 996     Sci-Fi          2013          8.7   456.39
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

In [5]:
df.columns

Index(['Movie Name', 'Genre', 'Release_Year', 'IMDb_Rating', 'Revenue'], dtype='object')

In [6]:
df.shape

(1000, 5)

In [7]:
df.sample()

  Movie Name   Genre  Release_Year  IMDb_Rating  Revenue
7    Movie 8  Comedy          2005          4.0  1062.13

In [8]:
df.dtypes

Movie Name       object
Genre            object
Release_Year      int64
IMDb_Rating     float64
Revenue         float64
dtype: object

In [9]:
df.info

<bound method DataFrame.info of      Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
4       Movie 5     Action          2012          6.6  1205.51
..          ...        ...           ...          ...      ...
995   Movie 996     Sci-Fi          2013          8.7   456.39
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[1000 rows x 5 columns]>

In [11]:
df.describe()

       Release_Year  IMDb_Rating     Revenue
count   1000.000000  1000.000000  1000.00000
mean    2001.782000     5.458600  1049.71626
std       12.671505     2.517714   586.32222
min     1980.000000     1.000000     2.63000
25%     1991.000000     3.300000   544.39500
50%     2001.000000     5.400000  1090.34000
75%     2012.000000     7.600000  1564.12250
max     2024.000000    10.000000  1999.70000

In [12]:
df.Genre

0         Sci-Fi
1      Adventure
2        Romance
3        Romance
4         Action
         ...
995       Sci-Fi
996    Adventure
997      Fantasy
998       Action
999       Horror
Name: Genre, Length: 1000, dtype: object

In [13]:
df[['Genre', 'IMDb_Rating', 'Revenue']]

         Genre  IMDb_Rating  Revenue
0       Sci-Fi          6.0  1680.53
1    Adventure          2.2   987.24
2      Romance          5.2  1122.13
3      Romance          4.5   581.84
4       Action          6.6  1205.51
..         ...          ...      ...
995     Sci-Fi          8.7   456.39
996  Adventure          6.2  1255.27
997    Fantasy          8.1  1161.96
998     Action          8.9   941.67
999     Horror          9.4  1390.70

[1000 rows x 3 columns]

In [15]:
# creating a new column based on another column
df['rank'] = df['IMDb_Rating'].rank()
df

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue   rank
0       Movie 1     Sci-Fi          2000          6.0  1680.53  568.5
1       Movie 2  Adventure          2000          2.2   987.24  132.0
2       Movie 3    Romance          2002          5.2  1122.13  471.5
3       Movie 4    Romance          2001          4.5   581.84  391.5
4       Movie 5     Action          2012          6.6  1205.51  647.5
..          ...        ...           ...          ...      ...    ...
995   Movie 996     Sci-Fi          2013          8.7   456.39  869.5
996   Movie 997  Adventure          1993          6.2  1255.27  594.5
997   Movie 998    Fantasy          2016          8.1  1161.96  801.5
998   Movie 999     Action          1996          8.9   941.67  896.5
999  Movie 1000     Horror          1995          9.4  1390.70  947.0

[1000 rows x 6 columns]

In [16]:
df.sort_values('rank')

    Movie Name      Genre  Release_Year  IMDb_Rating  Revenue   rank
955  Movie 956  Adventure          2019          1.0  1048.85    3.5
297  Movie 298     Comedy          2006          1.0   692.08    3.5
577  Movie 578     Action          1999          1.0  1621.75    3.5
80    Movie 81  Adventure          2002          1.0  1759.50    3.5
699  Movie 700   Thriller          1984          1.0     9.60    3.5
..         ...        ...           ...          ...      ...    ...
610  Movie 611    Mystery          2017         10.0  1355.06  997.5
564  Movie 565     Action          2020         10.0   943.50  997.5
106  Movie 107    Romance          2007         10.0  1837.45  997.5
472  Movie 473    Fantasy          1985         10.0   845.18  997.5
628  Movie 629    Mystery          1994         10.0   644.31  997.5

[1000 rows x 6 columns]

In [19]:
# renaming the column
df_rename = df.rename(columns = {'IMDb_Rating': 'Rating', 'Release_Year':'Year', 'rank':'Rank'})
df_rename

     Movie Name      Genre  Year  Rating  Revenue   Rank
0       Movie 1     Sci-Fi  2000     6.0  1680.53  568.5
1       Movie 2  Adventure  2000     2.2   987.24  132.0
2       Movie 3    Romance  2002     5.2  1122.13  471.5
3       Movie 4    Romance  2001     4.5   581.84  391.5
4       Movie 5     Action  2012     6.6  1205.51  647.5
..          ...        ...   ...     ...      ...    ...
995   Movie 996     Sci-Fi  2013     8.7   456.39  869.5
996   Movie 997  Adventure  1993     6.2  1255.27  594.5
997   Movie 998    Fantasy  2016     8.1  1161.96  801.5
998   Movie 999     Action  1996     8.9   941.67  896.5
999  Movie 1000     Horror  1995     9.4  1390.70  947.0

[1000 rows x 6 columns]

In [25]:
df

     Movie Name      Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1     Sci-Fi          2000          6.0  1680.53
1       Movie 2  Adventure          2000          2.2   987.24
2       Movie 3    Romance          2002          5.2  1122.13
3       Movie 4    Romance          2001          4.5   581.84
4       Movie 5     Action          2012          6.6  1205.51
..          ...        ...           ...          ...      ...
995   Movie 996     Sci-Fi          2013          8.7   456.39
996   Movie 997  Adventure          1993          6.2  1255.27
997   Movie 998    Fantasy          2016          8.1  1161.96
998   Movie 999     Action          1996          8.9   941.67
999  Movie 1000     Horror          1995          9.4  1390.70

[1000 rows x 5 columns]

In [27]:
df.Genre.unique()

array(['Sci-Fi', 'Adventure', 'Romance', 'Action', 'Fantasy', 'Mystery',
       'Comedy', 'Horror', 'Drama', 'Thriller'], dtype=object)

In [29]:
# Replacing specific value in a dataset
df['Genre'] = df.Genre.replace("Sci-Fi", "Scientific-Fiction")
df

     Movie Name               Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1  Scientific-Fiction          2000          6.0  1680.53
1       Movie 2           Adventure          2000          2.2   987.24
2       Movie 3             Romance          2002          5.2  1122.13
3       Movie 4             Romance          2001          4.5   581.84
4       Movie 5              Action          2012          6.6  1205.51
..          ...                 ...           ...          ...      ...
995   Movie 996  Scientific-Fiction          2013          8.7   456.39
996   Movie 997           Adventure          1993          6.2  1255.27
997   Movie 998             Fantasy          2016          8.1  1161.96
998   Movie 999              Action          1996          8.9   941.67
999  Movie 1000              Horror          1995          9.4  1390.70

[1000 rows x 5 columns]

In [30]:
df.dtypes

Movie Name       object
Genre            object
Release_Year      int64
IMDb_Rating     float64
Revenue         float64
dtype: object

In [32]:
# converting datatype
df["Genre"] = df["Genre"].astype("string")
df

     Movie Name               Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1  Scientific-Fiction          2000          6.0  1680.53
1       Movie 2           Adventure          2000          2.2   987.24
2       Movie 3             Romance          2002          5.2  1122.13
3       Movie 4             Romance          2001          4.5   581.84
4       Movie 5              Action          2012          6.6  1205.51
..          ...                 ...           ...          ...      ...
995   Movie 996  Scientific-Fiction          2013          8.7   456.39
996   Movie 997           Adventure          1993          6.2  1255.27
997   Movie 998             Fantasy          2016          8.1  1161.96
998   Movie 999              Action          1996          8.9   941.67
999  Movie 1000              Horror          1995          9.4  1390.70

[1000 rows x 5 columns]

In [33]:
df.dtypes

Movie Name              object
Genre           string[python]
Release_Year             int64
IMDb_Rating            float64
Revenue                float64
dtype: object

In [35]:
df.select_dtypes(include = ['float64', 'int64'])

     Release_Year  IMDb_Rating  Revenue
0            2000          6.0  1680.53
1            2000          2.2   987.24
2            2002          5.2  1122.13
3            2001          4.5   581.84
4            2012          6.6  1205.51
..            ...          ...      ...
995          2013          8.7   456.39
996          1993          6.2  1255.27
997          2016          8.1  1161.96
998          1996          8.9   941.67
999          1995          9.4  1390.70

[1000 rows x 3 columns]

In [36]:
df.describe(include = ['object', 'string'])

       Movie Name  Genre
count        1000   1000
unique        992     10
top      Movie 12  Drama
freq            2    113

In [37]:
df.describe(include = 'all')

       Movie Name  Genre  Release_Year  IMDb_Rating     Revenue
count        1000   1000   1000.000000  1000.000000  1000.00000
unique        992     10           NaN          NaN         NaN
top      Movie 12  Drama           NaN          NaN         NaN
freq            2    113           NaN          NaN         NaN
mean          NaN    NaN   2001.782000     5.458600  1049.71626
std           NaN    NaN     12.671505     2.517714   586.32222
min           NaN    NaN   1980.000000     1.000000     2.63000
25%           NaN    NaN   1991.000000     3.300000   544.39500
50%           NaN    NaN   2001.000000     5.400000  1090.34000
75%           NaN    NaN   2012.000000     7.600000  1564.12250
max           NaN    NaN   2024.000000    10.000000  1999.70000

In [38]:
df.Release_Year.value_counts()

Release_Year
2024    32
1989    30
2000    29
2007    29
1998    29
1985    28
1995    27
2013    26
1992    26
1996    26
1980    26
1999    25
2022    25
2003    25
2008    24
2002    24
2006    23
2011    23
1994    23
2015    23
2001    23
1997    22
2009    21
1990    21
2005    21
1991    21
1986    21
1993    21
1982    21
2004    20
2010    20
2012    20
2020    20
1988    20
2014    20
2018    18
2017    18
2023    18
1987    17
1981    17
1983    16
2021    16
1984    16
2019    15
2016    14
Name: count, dtype: int64

In [39]:
df.ndim

2

In [40]:
df.size

5000

In [41]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [42]:
df.corr

<bound method DataFrame.corr of      Movie Name               Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1  Scientific-Fiction          2000          6.0  1680.53
1       Movie 2           Adventure          2000          2.2   987.24
2       Movie 3             Romance          2002          5.2  1122.13
3       Movie 4             Romance          2001          4.5   581.84
4       Movie 5              Action          2012          6.6  1205.51
..          ...                 ...           ...          ...      ...
995   Movie 996  Scientific-Fiction          2013          8.7   456.39
996   Movie 997           Adventure          1993          6.2  1255.27
997   Movie 998             Fantasy          2016          8.1  1161.96
998   Movie 999              Action          1996          8.9   941.67
999  Movie 1000              Horror          1995          9.4  1390.70

[1000 rows x 5 columns]>

In [45]:
df['Genre'].nunique()

10

In [46]:
df['Revenue'].min()

2.63

In [47]:
df['Revenue'].max()

1999.7

In [48]:
df['Revenue'].mean()

np.float64(1049.71626)

In [49]:
df['Revenue'].var()

343773.7452008138

In [50]:
df['Revenue'].std()

586.3222196035332

In [52]:
print(df['Revenue'].sum())

1049716.26

In [55]:
df['Revenue'].median()

1090.3400000000001

In [56]:
df['Revenue'].mode()

0    1783.44
Name: Revenue, dtype: float64

In [53]:
# Checking the missing values
df.isnull().sum()
df.isna().sum()

Movie Name      0
Genre           0
Release_Year    0
IMDb_Rating     0
Revenue         0
dtype: int64

In [58]:
df.sort_index()

     Movie Name               Genre  Release_Year  IMDb_Rating  Revenue
0       Movie 1  Scientific-Fiction          2000          6.0  1680.53
1       Movie 2           Adventure          2000          2.2   987.24
2       Movie 3             Romance          2002          5.2  1122.13
3       Movie 4             Romance          2001          4.5   581.84
4       Movie 5              Action          2012          6.6  1205.51
..          ...                 ...           ...          ...      ...
995   Movie 996  Scientific-Fiction          2013          8.7   456.39
996   Movie 997           Adventure          1993          6.2  1255.27
997   Movie 998             Fantasy          2016          8.1  1161.96
998   Movie 999              Action          1996          8.9   941.67
999  Movie 1000              Horror          1995          9.4  1390.70

[1000 rows x 5 columns]